extends Resource
class_name BasementFloorFurnitureInventory

@export var objects := {
	# --- Replaced duplicates with Kitchen/LivingRoom versions ---
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxsofaCorner/Textures/FtrBoxsofaCorner_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxsofaCorner/FtrBoxsofaCorner.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxsofa/Textures/FtrBoxsofa_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxsofa/FtrBoxsofa.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxstool/Textures/FtrBoxstool_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxstool/FtrBoxstool.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCoolSofaL/Textures/FtrCoolSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCoolSofaL/FtrCoolSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrSofaL/Textures/FtrSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrSofaL/FtrSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicSofaL/Textures/FtrNordicSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicSofaL/FtrNordicSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrRattanChairS/Textures/FtrRattanChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrRattanChairS/FtrRattanChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrRockingchair/Textures/FtrRockingchair_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrRockingchair/FtrRockingchair.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleSofaL/Textures/FtrSimpleSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleSofaL/FtrSimpleSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleStoolS/Textures/FtrSimpleStoolS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleStoolS/FtrSimpleStoolS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueConsole/Textures/FtrAntiqueConsole_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueConsole/FtrAntiqueConsole.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicLowBoard/Textures/FtrNordicLowBoard_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicLowBoard/FtrNordicLowBoard.tscn",
	"res://Models/Final Models/Mudroom/FtrTVtray/Textures/FtrTVtray_icon.png": "res://Models/Final Models/Mudroom/FtrTVtray/FtrTVtray.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrElegantTableM/Textures/FtrElegantTableM_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrElegantTableM/FtrElegantTableM.tscn",
	"res://Models/Final Models/Bedrooms/FtrElegantChest/Textures/FtrElegantChest_icon.png": "res://Models/Final Models/Bedrooms/FtrElegantChest/FtrElegantChest.tscn",

	# --- Unique Basement items (unchanged) ---
	"res://Models/Final Models/Downstairs/FtrMoroccanStool/Textures/FtrMoroccanStool_icon.png": "res://Models/Final Models/Downstairs/FtrMoroccanStool/FtrMoroccanStool.tscn",
	"res://Models/Final Models/Downstairs/FtrPatchworkStoolS/Textures/FtrPatchworkStoolS_icon.png": "res://Models/Final Models/Downstairs/FtrPatchworkStoolS/FtrPatchworkStoolS.tscn",
	"res://Models/Final Models/Downstairs/FtrCushionJapanPile/Textures/FtrCushionJapanPile_icon.png": "res://Models/Final Models/Downstairs/FtrCushionJapanPile/FtrCushionJapanPile.tscn",
	"res://Models/Final Models/Downstairs/FtrPetBed/Textures/FtrPetBed_icon.png": "res://Models/Final Models/Downstairs/FtrPetBed/FtrPetBed.tscn",
	"res://Models/Final Models/Downstairs/FtrBoyChairS/Textures/FtrBoyChairS_icon.png": "res://Models/Final Models/Downstairs/FtrBoyChairS/FtrBoyChairS.tscn",
	"res://Models/Final Models/Downstairs/FtrCushionJapan/Textures/FtrCushionJapan_icon.png": "res://Models/Final Models/Downstairs/FtrCushionJapan/FtrCushionJapan.tscn",
	"res://Models/Final Models/Downstairs/FtrComponentHighclass/Textures/FtrComponentHighclass_icon.png": "res://Models/Final Models/Downstairs/FtrComponentHighclass/FtrComponentHighclass.tscn",
	"res://Models/Final Models/Downstairs/FtrComponentPro/Textures/FtrComponentPro_icon.png": "res://Models/Final Models/Downstairs/FtrComponentPro/FtrComponentPro.tscn",
	"res://Models/Final Models/Downstairs/FtrKaraoke/Textures/FtrKaraoke_icon.png": "res://Models/Final Models/Downstairs/FtrKaraoke/FtrKaraoke.tscn",
	"res://Models/Final Models/Tower/FtrLamp/Textures/FtrLamp_icon.png": "res://Models/Final Models/Tower/FtrLamp/FtrLamp.tscn",
	"res://Models/Final Models/Downstairs/FtrCoolTableS/Textures/FtrCoolTableS_icon.png": "res://Models/Final Models/Downstairs/FtrCoolTableS/FtrCoolTableS.tscn",
	"res://Models/Final Models/Downstairs/FtrIronwoodChest/Textures/FtrIronwoodChest_icon.png": "res://Models/Final Models/Downstairs/FtrIronwoodChest/FtrIronwoodChest.tscn",
	"res://Models/Final Models/Downstairs/FtrMoroccanTableS/Textures/FtrMoroccanTableS_icon.png": "res://Models/Final Models/Downstairs/FtrMoroccanTableS/FtrMoroccanTableS.tscn",
	"res://Models/Final Models/Downstairs/FtrCountryLowBoard/Textures/FtrCountryLowBoard_icon.png": "res://Models/Final Models/Downstairs/FtrCountryLowBoard/FtrCountryLowBoard.tscn",
	"res://Models/Final Models/Downstairs/FtrRattanTableS/Textures/FtrRattanTableS_icon.png": "res://Models/Final Models/Downstairs/FtrRattanTableS/FtrRattanTableS.tscn",
	"res://Models/Final Models/Downstairs/FtrSimpleChest/Textures/FtrSimpleChest_icon.png": "res://Models/Final Models/Downstairs/FtrSimpleChest/FtrSimpleChest.tscn",
	"res://Models/Final Models/Downstairs/FtrGardenTableSNatural/Textures/FtrGardenTableSNatural_icon.png": "res://Models/Final Models/Downstairs/FtrGardenTableSNatural/FtrGardenTableSNatural.tscn",
	"res://Models/Final Models/Entryway/FtrCountryTableM/Textures/FtrCountryTableM_icon.png": "res://Models/Final Models/Entryway/FtrCountryTableM/FtrCountryTableM.tscn",
	"res://Models/Final Models/Downstairs/FtrWoodenTableS/Textures/FtrWoodenTableS_icon.png": "res://Models/Final Models/Downstairs/FtrWoodenTableS/FtrWoodenTableS.tscn",
	"res://Models/Final Models/Downstairs/FtrWoodenChest/Textures/FtrWoodenChest_icon.png": "res://Models/Final Models/Downstairs/FtrWoodenChest/FtrWoodenChest.tscn",
	"res://Models/Final Models/Downstairs/FtrLowboardJapan/Textures/FtrLowboardJapan_icon.png": "res://Models/Final Models/Downstairs/FtrLowboardJapan/FtrLowboardJapan.tscn",
	"res://Models/Final Models/Downstairs/FtrProjectorscreen/Textures/FtrProjectorscreen_icon.png": "res://Models/Final Models/Downstairs/FtrProjectorscreen/FtrProjectorscreen.tscn",
	"res://Models/Final Models/Downstairs/FtrColorBoxShelfSide/Textures/FtrColorBoxShelfSide_icon.png": "res://Models/Final Models/Downstairs/FtrColorBoxShelfSide/FtrColorBoxShelfSide.tscn",
	"res://Models/Final Models/Downstairs/FtrColorBoxShelf/Textures/FtrColorBoxShelf_icon.png": "res://Models/Final Models/Downstairs/FtrColorBoxShelf/FtrColorBoxShelf.tscn",
	"res://Models/Final Models/Downstairs/FtrTrashboxWood/Textures/FtrTrashboxWood_icon.png": "res://Models/Final Models/Downstairs/FtrTrashboxWood/FtrTrashboxWood.tscn",
	"res://Models/Final Models/Downstairs/FtrCandymachine/Textures/FtrCandymachine_icon.png": "res://Models/Final Models/Downstairs/FtrCandymachine/FtrCandymachine.tscn",
	"res://Models/Final Models/Downstairs/FtrTablesoccer/Textures/FtrTablesoccer_icon.png": "res://Models/Final Models/Downstairs/FtrTablesoccer/FtrTablesoccer.tscn",
	"res://Models/Final Models/Downstairs/FtrPinball/Textures/FtrPinball_icon.png": "res://Models/Final Models/Downstairs/FtrPinball/FtrPinball.tscn",
	"res://Models/Final Models/Downstairs/FtrArcadegameFight/Textures/FtrArcadegameFight_icon.png": "res://Models/Final Models/Downstairs/FtrArcadegameFight/FtrArcadegameFight.tscn",
	"res://Models/Final Models/Downstairs/FtrSlideelephant/Textures/FtrSlideelephant_icon.png": "res://Models/Final Models/Downstairs/FtrSlideelephant/FtrSlideelephant.tscn",
	"res://Models/Final Models/Downstairs/FtrRockinghorse/Textures/FtrRockinghorse_icon.png": "res://Models/Final Models/Downstairs/FtrRockinghorse/FtrRockinghorse.tscn",
	"res://Models/Final Models/Downstairs/FtrRailroad/Textures/FtrRailroad_icon.png": "res://Models/Final Models/Downstairs/FtrRailroad/FtrRailroad.tscn",
	"res://Models/Final Models/Downstairs/FtrModelkitBox/Textures/FtrModelkitBox_icon.png": "res://Models/Final Models/Downstairs/FtrModelkitBox/FtrModelkitBox.tscn",
	"res://Models/Final Models/Downstairs/FtrLampMount/Textures/FtrLampMount_icon.png": "res://Models/Final Models/Downstairs/FtrLampMount/FtrLampMount.tscn",
	"res://Models/Final Models/Bedrooms/FtrAntiqueClock/Textures/FtrAntiqueClock_icon.png": "res://Models/Final Models/Bedrooms/FtrAntiqueClock/FtrAntiqueClock.tscn",
}
