extends Resource
class_name MudroomFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Mudroom/FtrDisplayClothesS/Textures/FtrDisplayClothesS_icon.png": "res://Models/Final Models/Mudroom/FtrDisplayClothesS/FtrDisplayClothesS.tscn",
	"res://Models/Final Models/Mudroom/FtrWashingmachineDrum/Textures/FtrWashingmachineDrum_icon.png": "res://Models/Final Models/Mudroom/FtrWashingmachineDrum/FtrWashingmachineDrum.tscn",
	"res://Models/Final Models/Mudroom/FtrClothesstand/Textures/FtrClothesstand_icon.png": "res://Models/Final Models/Mudroom/FtrClothesstand/FtrClothesstand.tscn",
	"res://Models/Final Models/Bathrooms/FtrPlasticChest/Textures/FtrPlasticChest_icon.png": "res://Models/Final Models/Bathrooms/FtrPlasticChest/FtrPlasticChest.tscn",
	"res://Models/Final Models/Mudroom/FtrRattanBasket/Textures/FtrRattanBasket_icon.png": "res://Models/Final Models/Mudroom/FtrRattanBasket/FtrRattanBasket.tscn",
	"res://Models/Final Models/Mudroom/FtrDisplayClothesM/Textures/FtrDisplayClothesM_icon.png": "res://Models/Final Models/Mudroom/FtrDisplayClothesM/FtrDisplayClothesM.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrBroadcastingTableLow/Textures/FtrBroadcastingTableLow_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrBroadcastingTableLow/FtrBroadcastingTableLow.tscn",
	"res://Models/Final Models/Downstairs/FtrTVtray/Textures/FtrTVtray_icon.png": "res://Models/Final Models/Downstairs/FtrTVtray/FtrTVtray.tscn",
	"res://Models/Final Models/Mudroom/FtrIronstand/Textures/FtrIronstand_icon.png": "res://Models/Final Models/Mudroom/FtrIronstand/FtrIronstand.tscn",
	"res://Models/Final Models/Mudroom/FtrRattanTrashbox/Textures/FtrRattanTrashbox_icon.png": "res://Models/Final Models/Mudroom/FtrRattanTrashbox/FtrRattanTrashbox.tscn",
	"res://Models/Final Models/Mudroom/FtrTrashboxWood/Textures/FtrTrashboxWood_icon.png": "res://Models/Final Models/Mudroom/FtrTrashboxWood/FtrTrashboxWood.tscn",
	#"res://Models/Final Models/Mudroom/FtrIron/Textures/FtrIron_icon.png": "res://Models/Final Models/Mudroom/FtrIron/FtrIron.tscn",
		#Rugs
	"res://Models/Final Models/Rugs/RugOtherCountryS00/Textures/RugOtherCountry_icon.png" : "res://Models/Final Models/Rugs/RugOtherCountryS00/RugOtherCountryS00.tscn",
	"res://Models/Final Models/Rugs/RugRectArgyleL01/Textures/RugRectArgyleL01_icon.png" : "res://Models/Final Models/Rugs/RugRectArgyleL01/RugRectArgyleL01.tscn",
	"res://Models/Final Models/Rugs/RugRectBathmatS00/Textures/RugRectBathmatS00_icon.png": "res://Models/Final Models/Rugs/RugRectBathmatS00/RugRectBathmatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectBorderL00/Textures/RugRectBorderL00_icon.png": "res://Models/Final Models/Rugs/RugRectBorderL00/RugRectBorderL00.tscn",
	"res://Models/Final Models/Rugs/RugRectBotanicalL00/Textures/RugRectBotanicalL00_icon.png" :"res://Models/Final Models/Rugs/RugRectBotanicalL00/RugRectBotanicalL00.tscn",
	"res://Models/Final Models/Rugs/RugRectChinamatS00/Textures/RugRectChinamatS00_icon.png" : "res://Models/Final Models/Rugs/RugRectChinamatS00/RugRectChinamatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDoormatS00/Textures/RugRectDoormatS00_icon.png" : "res://Models/Final Models/Rugs/RugRectDoormatS00/RugRectDoormatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDotL00/Textures/RugRectDotL00_icon.png" : "res://Models/Final Models/Rugs/RugRectDotL00/RugRectDotL00.tscn",
	"res://Models/Final Models/Rugs/RugRectElegantM00/Textures/RugRectElegantM00_icon.png" : "res://Models/Final Models/Rugs/RugRectElegantM00/RugRectElegantM00.tscn",
	"res://Models/Final Models/Rugs/RugRectEntranceS00/Textures/RugRectEntranceS00_icon.png" : "res://Models/Final Models/Rugs/RugRectEntranceS00/RugRectEntranceS00.tscn",
	"res://Models/Final Models/Rugs/RugRectJuneBrideM00/Textures/RugRectJuneBrideM00_icon.png" : "res://Models/Final Models/Rugs/RugRectJuneBrideM00/RugRectJuneBrideM00.tscn",
	"res://Models/Final Models/Rugs/RugRectKitchenS00/Textures/RugRectKitchenS00_icon.png" : "res://Models/Final Models/Rugs/RugRectKitchenS00/RugRectKitchenS00.tscn",
	#"res://Models/Final Models/Rugs/RugRectPatternS00/Textures/RugRectPatternS00_icon.png" : "res://Models/Final Models/Rugs/RugRectPatternS00/RugRectPatternS00.tscn",
	"res://Models/Final Models/Rugs/RugRectPiratesM00/Textures/RugRectPiratesM00_icon.png" : "res://Models/Final Models/Rugs/RugRectPiratesM00/RugRectPiratesM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundLaceM00/Textures/RugRoundLaceM00_icon.png" : "res://Models/Final Models/Rugs/RugRoundLaceM00/RugRoundLaceM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleM00/Textures/RugRoundSimpleM00_icon.png" : "res://Models/Final Models/Rugs/RugRoundSimpleM00/RugRoundSimpleM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleS00/Textures/RugRoundSimpleS00_icon.png" : "res://Models/Final Models/Rugs/RugRoundSimpleS00/RugRoundSimpleS00.tscn",
	#"res://Models/Final Models/Rugs/RugSquareChristmasL00/Textures/RugSquareChristmasL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareChristmasL00/RugSquareChristmasL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareElegantL00/Textures/RugSquareElegantL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareElegantL00/RugSquareElegantL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHalloweenL00/Textures/RugSquareHalloweenL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHalloweenL00/RugSquareHalloweenL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHarvestL00/Textures/RugSquareHarvestL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHarvestL00/RugSquareHarvestL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHawaiianL00/Textures/RugSquareHawaiianL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHawaiianL00/RugSquareHawaiianL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareKirimL00/Textures/RugSquareKirimL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareKirimL00/RugSquareKirimL00.tscn",
	#"res://Models/Final Models/Rugs/RugSquarePatternL00/Textures/mMaRugSquarePatternL00_icon.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquarePersianL01/Textures/RugSquarePersianL01_icon.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleM01/Textures/RugSquareSimpleM01_icon.png" : "res://Models/Final Models/Rugs/RugSquareSimpleM01/RugSquareSimpleM01.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleS01/Textures/RugSquareSimpleS01_icon.png" : "res://Models/Final Models/Rugs/RugSquareSimpleS01/RugSquareSimpleS01.tscn",
	
}
