extends Resource
class_name TripleThreatFloorFurnitureInventory

@export var objects := {
	# --- Kitchen ---
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCountryCupboard/Textures/FtrCountryCupboard_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCountryCupboard/FtrCountryCupboard.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrRefrigeratorDoubledoor/Textures/FtrRefrigeratorDoubledoor_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrRefrigeratorDoubledoor/FtrRefrigeratorDoubledoor.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrKitchenCompact/Textures/FtrKitchenCompact_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrKitchenCompact/FtrKitchenCompact.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrKitchenOven/Textures/FtrKitchenOven_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrKitchenOven/FtrKitchenOven.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrIronwoodCupboard/Textures/FtrIronwoodCupboard_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrIronwoodCupboard/FtrIronwoodCupboard.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrIronwoodKitchen/Textures/FtrIronwoodKitchen_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrIronwoodKitchen/FtrIronwoodKitchen.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrKitchenIsland/Textures/FtrKitchenIsland_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrKitchenIsland/FtrKitchenIsland.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrKitchenStainless/Textures/FtrKitchenStainless_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrKitchenStainless/FtrKitchenStainless.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCountryKitchen/Textures/FtrCountryKitchen_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCountryKitchen/FtrCountryKitchen.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrRefrigerator/Textures/FtrRefrigerator_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrRefrigerator/FtrRefrigerator.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCounter/Textures/FtrCounter_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCounter/FtrCounter.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCounterchair/Textures/FtrCounterchair_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCounterchair/FtrCounterchair.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrAmeretroCounterchair/Textures/FtrAmeretroCounterchair_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrAmeretroCounterchair/FtrAmeretroCounterchair.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrVintageChairS/Textures/FtrVintageChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrVintageChairS/FtrVintageChairS.tscn",

	# --- Dining Room ---
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrBabychairHigh/Textures/FtrBabychairHigh_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrBabychairHigh/FtrBabychairHigh.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueTableL/Textures/FtrAntiqueTableL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueTableL/FtrAntiqueTableL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCoolTableL/Textures/FtrCoolTableL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCoolTableL/FtrCoolTableL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrIronwoodTableL/Textures/FtrIronwoodTableL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrIronwoodTableL/FtrIronwoodTableL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrTableSquareSimpleL/Textures/FtrTableSquareSimpleL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrTableSquareSimpleL/FtrTableSquareSimpleL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicTableL/Textures/FtrNordicTableL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicTableL/FtrNordicTableL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrTableCloth/Textures/FtrTableCloth_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrTableCloth/FtrTableCloth.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrWoodenTableL/Textures/FtrWoodenTableL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrWoodenTableL/FtrWoodenTableL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrHarvestTableL/Textures/FtrHarvestTableL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrHarvestTableL/FtrHarvestTableL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueChairS/Textures/FtrAntiqueChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueChairS/FtrAntiqueChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCoolChairS/Textures/FtrCoolChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCoolChairS/FtrCoolChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCuteChairS/Textures/FtrCuteChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCuteChairS/FtrCuteChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrChineseChair/Textures/FtrChineseChair_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrChineseChair/FtrChineseChair.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCountryChairS/Textures/FtrCountryChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCountryChairS/FtrCountryChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrHarvestChairS/Textures/FtrHarvestChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrHarvestChairS/FtrHarvestChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrWoodenChairS/Textures/FtrWoodenChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrWoodenChairS/FtrWoodenChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleChairS/Textures/FtrSimpleChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleChairS/FtrSimpleChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxsofa/Textures/FtrBoxsofa_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxsofa/FtrBoxsofa.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxsofaCorner/Textures/FtrBoxsofaCorner_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxsofaCorner/FtrBoxsofaCorner.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxstool/Textures/FtrBoxstool_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrBoxstool/FtrBoxstool.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCoolSofaL/Textures/FtrCoolSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCoolSofaL/FtrCoolSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrCuteChairL/Textures/FtrCuteChairL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrCuteChairL/FtrCuteChairL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrSofaL/Textures/FtrSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrSofaL/FtrSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrMoroccanSofaL/Textures/FtrMoroccanSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrMoroccanSofaL/FtrMoroccanSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicSofaL/Textures/FtrNordicSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicSofaL/FtrNordicSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrRattanChairS/Textures/FtrRattanChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrRattanChairS/FtrRattanChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrRockingchair/Textures/FtrRockingchair_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrRockingchair/FtrRockingchair.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleSofaL/Textures/FtrSimpleSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleSofaL/FtrSimpleSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleStoolS/Textures/FtrSimpleStoolS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrSimpleStoolS/FtrSimpleStoolS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrVintageSofaL/Textures/FtrVintageSofaL_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrVintageSofaL/FtrVintageSofaL.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueConsole/Textures/FtrAntiqueConsole_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueConsole/FtrAntiqueConsole.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueTableS/Textures/FtrAntiqueTableS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrAntiqueTableS/FtrAntiqueTableS.tscn",
	"res://Models/Final Models/Tower/FtrLamp/Textures/FtrLamp_icon.png": "res://Models/Final Models/Tower/FtrLamp/FtrLamp.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrDrawingTable/Textures/FtrDrawingTable_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrDrawingTable/FtrDrawingTable.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrElegantTableM/Textures/FtrElegantTableM_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrElegantTableM/FtrElegantTableM.tscn",
	"res://Models/Final Models/Entryway/FtrElegantMirror/Textures/FtrElegantMirror_icon.png": "res://Models/Final Models/Entryway/FtrElegantMirror/FtrElegantMirror.tscn",
	"res://Models/Final Models/Tower/FtrElegantSofaL/Textures/FtrElegantSofaL_icon.png": "res://Models/Final Models/Tower/FtrElegantSofaL/FtrElegantSofaL.tscn",
	"res://Models/Final Models/Bedrooms/FtrElegantChest/Textures/FtrElegantChest_icon.png": "res://Models/Final Models/Bedrooms/FtrElegantChest/FtrElegantChest.tscn",
	"res://Models/Final Models/Tower/FtrElegantChairS/Textures/FtrElegantChairS_icon.png" : "res://Models/Final Models/Tower/FtrElegantChairS/FtrElegantChairS.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicLowBoard/Textures/FtrNordicLowBoard_icon.png":"res://Models/Final Models/KitchenDiningLivingRoom/FtrNordicLowBoard/FtrNordicLowBoard.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrFireplace/Textures/FtrFireplace_icon.png":"res://Models/Final Models/KitchenDiningLivingRoom/FtrFireplace/FtrFireplace.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrHarvestFireplace/Textures/FtrHarvestFireplace_icon.png":"res://Models/Final Models/KitchenDiningLivingRoom/FtrHarvestFireplace/FtrHarvestFireplace.tscn",
	"res://Models/Final Models/Mudroom/FtrTVtray/Textures/FtrTVtray_icon.png":"res://Models/Final Models/Mudroom/FtrTVtray/FtrTVtray.tscn",
	"res://Models/Final Models/Downstairs/FtrCountryLowBoard/Textures/FtrCountryLowBoard_icon.png": "res://Models/Final Models/Downstairs/FtrCountryLowBoard/FtrCountryLowBoard.tscn",
	"res://Models/Final Models/Downstairs/FtrPetBed/Textures/FtrPetBed_icon.png": "res://Models/Final Models/Downstairs/FtrPetBed/FtrPetBed.tscn",
}
