extends Resource
class_name BedroomsFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Bedrooms/FtrBabybed/Textures/FtrBabybed_icon.png": "res://Models/Final Models/Bedrooms/FtrBabybed/FtrBabybed.tscn",
	"res://Models/Final Models/Bedrooms/FtrBabychair/Textures/FtrBabychair_icon.png": "res://Models/Final Models/Bedrooms/FtrBabychair/FtrBabychair.tscn",
	"res://Models/Final Models/Bedrooms/FtrDreamyBedS/Textures/FtrDreamyBedS_icon.png": "res://Models/Final Models/Bedrooms/FtrDreamyBedS/FtrDreamyBedS.tscn",
	"res://Models/Final Models/Bedrooms/FtrDreamyShelf/Textures/FtrDreamyShelf_icon.png": "res://Models/Final Models/Bedrooms/FtrDreamyShelf/FtrDreamyShelf.tscn",
	"res://Models/Final Models/Bedrooms/FtrSlideelephant/Textures/FtrSlideelephant_icon.png": "res://Models/Final Models/Bedrooms/FtrSlideelephant/FtrSlideelephant.tscn",
	#not feeling it "res://Models/Final Models/Bedrooms/FtrFan/Textures/FtrFan_icon.png": "res://Models/Final Models/Bedrooms/FtrFan/FtrFan.tscn",
	"res://Models/Final Models/Bedrooms/FtrFrogchair/Textures/FtrFrogchair_icon.png": "res://Models/Final Models/Bedrooms/FtrFrogchair/FtrFrogchair.tscn",
	"res://Models/Final Models/Office/FtrGamingDesk/Textures/FtrGamingDesk_icon.png": "res://Models/Final Models/Office/FtrGamingDesk/FtrGamingDesk.tscn",
	"res://Models/Final Models/Office/FtrGamingChair/Textures/FtrGamingChair_icon.png": "res://Models/Final Models/Office/FtrGamingChair/FtrGamingChair.tscn",
	#its godzirraaaaa "res://Models/Final Models/Bedrooms/FtrBearXL/Textures/FtrBearXL_icon.png": "res://Models/Final Models/Bedrooms/FtrBearXL/FtrBearXL.tscn",
	"res://Models/Final Models/Downstairs/FtrColorBoxShelf/Textures/FtrColorBoxShelf_icon.png": "res://Models/Final Models/Downstairs/FtrColorBoxShelf/FtrColorBoxShelf.tscn",
	"res://Models/Final Models/Downstairs/FtrColorBoxShelfSide/Textures/FtrColorBoxShelfSide_icon.png": "res://Models/Final Models/Downstairs/FtrColorBoxShelfSide/FtrColorBoxShelfSide.tscn",
	"res://Models/Final Models/Bedrooms/FtrBeddesk/Textures/FtrBeddesk_icon.png": "res://Models/Final Models/Bedrooms/FtrBeddesk/FtrBeddesk.tscn",
	"res://Models/Final Models/Bedrooms/FtrBearM/Textures/FtrBearM_icon.png": "res://Models/Final Models/Bedrooms/FtrBearM/FtrBearM.tscn",
	"res://Models/Final Models/Bedrooms/FtrPandaM/Textures/FtrPandaM_icon.png": "res://Models/Final Models/Bedrooms/FtrPandaM/FtrPandaM.tscn",
	"res://Models/Final Models/Tower/FtrOpenshelfWood/Textures/FtrOpenshelfWood_icon.png": "res://Models/Final Models/Tower/FtrOpenshelfWood/FtrOpenshelfWood.tscn",
	#too big "res://Models/Final Models/Bedrooms/FtrBearL/Textures/FtrBearL_icon.png": "res://Models/Final Models/Bedrooms/FtrBearL/FtrBearL.tscn",
	#too big "res://Models/Final Models/Bedrooms/FtrPandaL/Textures/FtrPandaL_icon.png": "res://Models/Final Models/Bedrooms/FtrPandaL/FtrPandaL.tscn",
	"res://Models/Final Models/Tower/FtrStudyChair/Textures/FtrStudyChair_icon.png": "res://Models/Final Models/Tower/FtrStudyChair/FtrStudyChair.tscn",
	"res://Models/Final Models/Tower/FtrBookshelf/Textures/FtrBookshelf_icon.png": "res://Models/Final Models/Tower/FtrBookshelf/FtrBookshelf.tscn",
	"res://Models/Final Models/KitchenDiningLivingRoom/FtrWoodenChairS/Textures/FtrWoodenChairS_icon.png": "res://Models/Final Models/KitchenDiningLivingRoom/FtrWoodenChairS/FtrWoodenChairS.tscn",
	"res://Models/Final Models/Entryway/FtrWoodenChest/Textures/FtrWoodenChest_icon.png": "res://Models/Final Models/Entryway/FtrWoodenChest/FtrWoodenChest.tscn",
	"res://Models/Final Models/Bedrooms/FtrWoodenBedW/Textures/FtrWoodenBedW_icon.png": "res://Models/Final Models/Bedrooms/FtrWoodenBedW/FtrWoodenBedW.tscn",
	"res://Models/Final Models/Bedrooms/FtrWoodenTableS/Textures/FtrWoodenTableS_icon.png": "res://Models/Final Models/Bedrooms/FtrWoodenTableS/FtrWoodenTableS.tscn",
	"res://Models/Final Models/Bedrooms/FtrWoodenTableMini/Textures/FtrWoodenTableMini_icon.png": "res://Models/Final Models/Bedrooms/FtrWoodenTableMini/FtrWoodenTableMini.tscn",
	"res://Models/Final Models/Bedrooms/FtrWoodenBedS/Textures/FtrWoodenBedS_icon.png": "res://Models/Final Models/Bedrooms/FtrWoodenBedS/FtrWoodenBedS.tscn",
	"res://Models/Final Models/Bedrooms/FtrWoodenCloset/Textures/FtrWoodenCloset_icon.png": "res://Models/Final Models/Bedrooms/FtrWoodenCloset/FtrWoodenCloset.tscn",
	"res://Models/Final Models/Bedrooms/FtrTrashboxWood/Textures/FtrTrashboxWood_icon.png": "res://Models/Final Models/Bedrooms/FtrTrashboxWood/FtrTrashboxWood.tscn",
	#"res://Models/Final Models/Bedrooms/FtrCrsPopupbook/Textures/FtrCrsPopupbook_icon.png": "res://Models/Final Models/Bedrooms/FtrCrsPopupbook/FtrCrsPopupbook.tscn",
	"res://Models/Final Models/Bedrooms/FtrToybox/Textures/FtrToybox_icon.png": "res://Models/Final Models/Bedrooms/FtrToybox/FtrToybox.tscn",
	"res://Models/Final Models/Tower/FtrLamp/Textures/FtrLamp_icon.png": "res://Models/Final Models/Tower/FtrLamp/FtrLamp.tscn",
	"res://Models/Final Models/Bedrooms/FtrLampMount/Textures/FtrLampMount_icon.png": "res://Models/Final Models/Bedrooms/FtrLampMount/FtrLampMount.tscn",
	"res://Models/Final Models/Bedrooms/FtrAntiqueBedW/Textures/FtrAntiqueBedW_icon.png": "res://Models/Final Models/Bedrooms/FtrAntiqueBedW/FtrAntiqueBedW.tscn",
	"res://Models/Final Models/Bedrooms/FtrCoolBedS/Textures/FtrCoolBedS_icon.png": "res://Models/Final Models/Bedrooms/FtrCoolBedS/FtrCoolBedS.tscn",
	#frick no "res://Models/Final Models/Bedrooms/FtrCuteBedW/Textures/FtrCuteBedW_icon.png": "res://Models/Final Models/Bedrooms/FtrCuteBedW/FtrCuteBedW.tscn",
	"res://Models/Final Models/Bedrooms/FtrElegantBedW/Textures/FtrElegantBedW_icon.png": "res://Models/Final Models/Bedrooms/FtrElegantBedW/FtrElegantBedW.tscn",
	"res://Models/Final Models/Bedrooms/FtrIronwoodBedS/Textures/FtrIronwoodBedS_icon.png": "res://Models/Final Models/Bedrooms/FtrIronwoodBedS/FtrIronwoodBedS.tscn",
	"res://Models/Final Models/Bedrooms/FtrLogBedW/Textures/FtrLogBedW_icon.png": "res://Models/Final Models/Bedrooms/FtrLogBedW/FtrLogBedW.tscn",
	"res://Models/Final Models/Bedrooms/FtrCountryBedS/Textures/FtrCountryBedS_icon.png": "res://Models/Final Models/Bedrooms/FtrCountryBedS/FtrCountryBedS.tscn",
	"res://Models/Final Models/Bedrooms/FtrRattanBedW/Textures/FtrRattanBedW_icon.png": "res://Models/Final Models/Bedrooms/FtrRattanBedW/FtrRattanBedW.tscn",
	"res://Models/Final Models/Bedrooms/FtrSimpleBedS/Textures/FtrSimpleBedS_icon.png": "res://Models/Final Models/Bedrooms/FtrSimpleBedS/FtrSimpleBedS.tscn",
	"res://Models/Final Models/Bedrooms/FtrAntiqueChest/Textures/FtrAntiqueChest_icon.png": "res://Models/Final Models/Bedrooms/FtrAntiqueChest/FtrAntiqueChest.tscn",
	"res://Models/Final Models/Bedrooms/FtrCuteClosetLR/Textures/FtrCuteClosetLR_icon.png": "res://Models/Final Models/Bedrooms/FtrCuteClosetLR/FtrCuteClosetLR.tscn",
	"res://Models/Final Models/Bedrooms/FtrIronwoodChest/Textures/FtrIronwoodChest_icon.png": "res://Models/Final Models/Bedrooms/FtrIronwoodChest/FtrIronwoodChest.tscn",
	"res://Models/Final Models/Bedrooms/FtrCountryClosetLR/Textures/FtrCountryClosetLR_icon.png": "res://Models/Final Models/Bedrooms/FtrCountryClosetLR/FtrCountryClosetLR.tscn",
	"res://Models/Final Models/Bedrooms/FtrRattanClosetLR/Textures/FtrRattanClosetLR_icon.png": "res://Models/Final Models/Bedrooms/FtrRattanClosetLR/FtrRattanClosetLR.tscn",
	"res://Models/Final Models/Bedrooms/FtrSimpleChest/Textures/FtrSimpleChest_icon.png": "res://Models/Final Models/Bedrooms/FtrSimpleChest/FtrSimpleChest.tscn",
	"res://Models/Final Models/Bedrooms/FtrDrawingTable/Textures/FtrDrawingTable_icon.png": "res://Models/Final Models/Bedrooms/FtrDrawingTable/FtrDrawingTable.tscn",
	"res://Models/Final Models/Bedrooms/FtrBlockShelf/Textures/FtrBlockShelf_icon.png": "res://Models/Final Models/Bedrooms/FtrBlockShelf/FtrBlockShelf.tscn",
	"res://Models/Final Models/Bedrooms/FtrAntiqueTableS/Textures/FtrAntiqueTableS_icon.png": "res://Models/Final Models/Bedrooms/FtrAntiqueTableS/FtrAntiqueTableS.tscn",
	"res://Models/Final Models/Bedrooms/FtrElegantMirror/Textures/FtrElegantMirror_icon.png": "res://Models/Final Models/Bedrooms/FtrElegantMirror/FtrElegantMirror.tscn",
	"res://Models/Final Models/Bedrooms/FtrAcorsticguitar/Textures/FtrAcorsticguitar_icon.png": "res://Models/Final Models/Bedrooms/FtrAcorsticguitar/FtrAcorsticguitar.tscn",
	"res://Models/Final Models/Bedrooms/FtrAntiqueClock/Textures/FtrAntiqueClock_icon.png": "res://Models/Final Models/Bedrooms/FtrAntiqueClock/FtrAntiqueClock.tscn",
	"res://Models/Final Models/Bedrooms/FtrAmp/Textures/FtrAmp_icon.png": "res://Models/Final Models/Bedrooms/FtrAmp/FtrAmp.tscn",
	"res://Models/Final Models/Downstairs/FtrElegantChest/Textures/FtrElegantChest_icon.png": "res://Models/Final Models/Downstairs/FtrElegantChest/FtrElegantChest.tscn",
	"res://Models/Final Models/Bedrooms/FtrSimpleTableM/Textures/FtrSimpleTableM_icon.png": "res://Models/Final Models/Bedrooms/FtrSimpleTableM/FtrSimpleTableM.tscn"
}
