extends Resource
class_name EntrywayFloorFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Entryway/FtrElegantMirror/Textures/FtrElegantMirror_icon.png": "res://Models/Final Models/Entryway/FtrElegantMirror/FtrElegantMirror.tscn",
	"res://Models/Final Models/Entryway/FtrIronHanger/Textures/FtrIronHanger_icon.png": "res://Models/Final Models/Entryway/FtrIronHanger/FtrIronHanger.tscn",
	"res://Models/Final Models/Entryway/FtrAntiqueConsole/Textures/FtrAntiqueConsole_icon.png": "res://Models/Final Models/Entryway/FtrAntiqueConsole/FtrAntiqueConsole.tscn",
	"res://Models/Final Models/Entryway/FtrAntiqueTableS/Textures/FtrAntiqueTableS_icon.png": "res://Models/Final Models/Entryway/FtrAntiqueTableS/FtrAntiqueTableS.tscn",
	"res://Models/Final Models/Entryway/FtrIrongardenTable/Textures/FtrIrongardenTable_icon.png": "res://Models/Final Models/Entryway/FtrIrongardenTable/FtrIrongardenTable.tscn",
	"res://Models/Final Models/Entryway/FtrAlumiwoodtable/Textures/FtrAlumiwoodtable_icon.png": "res://Models/Final Models/Entryway/FtrAlumiwoodtable/FtrAlumiwoodtable.tscn",
	"res://Models/Final Models/Entryway/FtrMoroccanTableS/Textures/FtrMoroccanTableS_icon.png": "res://Models/Final Models/Entryway/FtrMoroccanTableS/FtrMoroccanTableS.tscn",
	"res://Models/Final Models/Entryway/FtrGardenTableSNatural/Textures/FtrGardenTableSNatural_icon.png": "res://Models/Final Models/Entryway/FtrGardenTableSNatural/FtrGardenTableSNatural.tscn",
	"res://Models/Final Models/Entryway/FtrCountryTableM/Textures/FtrCountryTableM_icon.png": "res://Models/Final Models/Entryway/FtrCountryTableM/FtrCountryTableM.tscn",
	"res://Models/Final Models/Entryway/FtrRattanTableS/Textures/FtrRattanTableS_icon.png": "res://Models/Final Models/Entryway/FtrRattanTableS/FtrRattanTableS.tscn",
	"res://Models/Final Models/Entryway/FtrTableSquareSimpleS/Textures/FtrTableSquareSimpleS_icon.png": "res://Models/Final Models/Entryway/FtrTableSquareSimpleS/FtrTableSquareSimpleS.tscn",
	"res://Models/Final Models/Entryway/FtrRoundTableClothS/Textures/FtrRoundTableClothS_icon.png": "res://Models/Final Models/Entryway/FtrRoundTableClothS/FtrRoundTableClothS.tscn",
	"res://Models/Final Models/Entryway/FtrWoodenChest/Textures/FtrWoodenChest_icon.png": "res://Models/Final Models/Entryway/FtrWoodenChest/FtrWoodenChest.tscn",
	"res://Models/Final Models/Entryway/FtrLowtableJapan/Textures/FtrLowtableJapan_icon.png": "res://Models/Final Models/Entryway/FtrLowtableJapan/FtrLowtableJapan.tscn",
	"res://Models/Final Models/Entryway/FtrMirrorBig/Textures/FtrMirrorBig_icon.png" :"res://Models/Final Models/Entryway/FtrMirrorBig/FtrMirrorBig.tscn",
	
	#Rugs
	"res://Models/Final Models/Rugs/RugOtherCountryS00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugOtherCountryS00/RugOtherCountryS00.tscn",
	"res://Models/Final Models/Rugs/RugRectArgyleL01/Textures/mMain_Alb.png" :"res://Models/Final Models/Rugs/RugRectArgyleL01/RugRectArgyleL01.tscn",
	"res://Models/Final Models/Rugs/RugRectBathmatS00/Textures/mMain_Alb.png": "res://Models/Final Models/Rugs/RugRectBathmatS00/RugRectBathmatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectBorderL00/Textures/mMain_Alb.png": "res://Models/Final Models/Rugs/RugRectBorderL00/RugRectBorderL00.tscn",
	"res://Models/Final Models/Rugs/RugRectBotanicalL00/Textures/mMain_Alb.png" :"res://Models/Final Models/Rugs/RugRectBotanicalL00/RugRectBotanicalL00.tscn",
	"res://Models/Final Models/Rugs/RugRectChinamatS00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectChinamatS00/RugRectChinamatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDoormatS00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectDoormatS00/RugRectDoormatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDotL00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectDotL00/RugRectDotL00.tscn",
	"res://Models/Final Models/Rugs/RugRectElegantM00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectElegantM00/RugRectElegantM00.tscn",
	"res://Models/Final Models/Rugs/RugRectEntranceS00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectEntranceS00/RugRectEntranceS00.tscn",
	"res://Models/Final Models/Rugs/RugRectJuneBrideM00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectJuneBrideM00/RugRectJuneBrideM00.tscn",
	"res://Models/Final Models/Rugs/RugRectKitchenS00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectKitchenS00/RugRectKitchenS00.tscn",
	"res://Models/Final Models/Rugs/RugRectPatternS00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectPatternS00/RugRectPatternS00.tscn",
	"res://Models/Final Models/Rugs/RugRectPiratesM00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRectPiratesM00/RugRectPiratesM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundLaceM00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRoundLaceM00/RugRoundLaceM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleM00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRoundSimpleM00/RugRoundSimpleM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleS00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugRoundSimpleS00/RugRoundSimpleS00.tscn",
	"res://Models/Final Models/Rugs/RugSquareChristmasL00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquareChristmasL00/RugSquareChristmasL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareElegantL00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquareElegantL00/RugSquareElegantL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHalloweenL00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquareHalloweenL00/RugSquareHalloweenL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHarvestL00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquareHarvestL00/RugSquareHarvestL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHawaiianL00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquareHawaiianL00/RugSquareHawaiianL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareKirimL00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquareKirimL00/RugSquareKirimL00.tscn",
	"res://Models/Final Models/Rugs/RugSquarePatternL00/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquarePersianL01/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleM01/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquareSimpleM01/RugSquareSimpleM01.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleS01/Textures/mMain_Alb.png" : "res://Models/Final Models/Rugs/RugSquareSimpleS01/RugSquareSimpleS01.tscn",
	
}
