extends Resource
class_name WallPaperInventory

@export var objects := {
	"res://Floor and Wall Textures/Wall0/RoomTexWallSimple00_Alb.png": preload("res://Floor and Wall Textures/Wall0/Wall0.tres"),
	"res://Floor and Wall Textures/Wall1/RoomTexWallSimple01_Alb.png": preload("res://Floor and Wall Textures/Wall1/Wall1.tres"),
	"res://Floor and Wall Textures/Wall2/RoomTexWallSimple02_Alb.png": preload("res://Floor and Wall Textures/Wall2/Wall2.tres"),
	"res://Floor and Wall Textures/Wall3/RoomTexWallSimple03_Alb.png": preload("res://Floor and Wall Textures/Wall3/Wall3.tres"),
	"res://Floor and Wall Textures/Wall4/RoomTexWallStripe04.Nin_NX_NVN/RoomTexWallStripe04_Alb.png": preload("res://Floor and Wall Textures/Wall4/Wall4.tres"),
	"res://Floor and Wall Textures/Wall23/RoomTexWallStripe03_Alb.png": preload("res://Floor and Wall Textures/Wall23/Wall23.tres"),
	"res://Floor and Wall Textures/Wall8/RoomTexWallDot01_Alb.png": preload("res://Floor and Wall Textures/Wall8/Wall8.tres"),
	"res://Floor and Wall Textures/Wall10/RoomTexWallDot00_Alb.png": preload("res://Floor and Wall Textures/Wall10/Wall10.tres"),
	"res://Floor and Wall Textures/Wall27/RoomTexWallCountry00_Alb.png": preload("res://Floor and Wall Textures/Wall27/Wall27.tres"),
	"res://Floor and Wall Textures/Wall7/RoomTexWallCountry01.Nin_NX_NVN/RoomTexWallCountry01_Alb.png": preload("res://Floor and Wall Textures/Wall7/Wall7.tres"),
	"res://Floor and Wall Textures/Wall25/RoomTexWallCountry02_Alb.png": preload("res://Floor and Wall Textures/Wall25/Wall25.tres"),
	"res://Floor and Wall Textures/Wall14/RoomTexWallCountry03_Alb.png": preload("res://Floor and Wall Textures/Wall14/Wall14.tres"),
	"res://Floor and Wall Textures/Wall17/RoomTexWallCute00_Alb.png": preload("res://Floor and Wall Textures/Wall17/Wall17.tres"),
	"res://Floor and Wall Textures/Wall16/RoomTexWallCute03_Alb.png": preload("res://Floor and Wall Textures/Wall16/Wall16.tres"),
	"res://Floor and Wall Textures/Wall18/RoomTexWallCute01_Alb.png": preload("res://Floor and Wall Textures/Wall18/Wall18.tres"),
	"res://Floor and Wall Textures/Wall19/RoomTexWallCute02_Alb.png": preload("res://Floor and Wall Textures/Wall19/Wall19.tres"),
	"res://Floor and Wall Textures/Wall5/RoomTexWallHall02.Nin_NX_NVN/RoomTexWallHall02_Alb.png": preload("res://Floor and Wall Textures/Wall5/Wall5.tres"),
	"res://Floor and Wall Textures/Wall9/RoomTexWallPanelMold00_Alb.png": preload("res://Floor and Wall Textures/Wall9/Wall9.tres"),
	"res://Floor and Wall Textures/Wall15/RoomTexWallPanelMold02_Alb.png": preload("res://Floor and Wall Textures/Wall15/Wall15.tres"),
	"res://Floor and Wall Textures/Wall20/RoomTexWallHall01_Alb.png": preload("res://Floor and Wall Textures/Wall20/Wall20.tres"),
	"res://Floor and Wall Textures/Wall22/RoomTexWallHall00_Alb.png": preload("res://Floor and Wall Textures/Wall22/Wall22.tres"),
	"res://Floor and Wall Textures/Wall24/RoomTexWallPanelMold01_Alb.png": preload("res://Floor and Wall Textures/Wall24/Wall24.tres"),
	"res://Floor and Wall Textures/Wall26/RoomTexWallHall03_Alb.png": preload("res://Floor and Wall Textures/Wall26/Wall26.tres"),
	"res://Floor and Wall Textures/Wall6/RoomTexWallMud01.Nin_NX_NVN/RoomTexWallMud01_Alb.png": preload("res://Floor and Wall Textures/Wall6/Wall6.tres"),
	"res://Floor and Wall Textures/Wall21/RoomTexWallMud03_Alb.png": preload("res://Floor and Wall Textures/Wall21/Wall21.tres"),
	"res://Floor and Wall Textures/Wall11/RoomTexWallMud02_Alb.png": preload("res://Floor and Wall Textures/Wall11/Wall11.tres"),
	"res://Floor and Wall Textures/Wall28/RoomTexWallArtDeco00_Alb.png": preload("res://Floor and Wall Textures/Wall28/Wall28.tres"),
}
