extends Resource
class_name SittingRoomFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Tower/FtrArmor/Textures/FtrArmor_icon.png": "res://Models/Final Models/Tower/FtrArmor/FtrArmor.tscn",
	"res://Models/Final Models/Tower/FtrAntiqueDresser/Textures/FtrAntiqueDresser_icon.png": "res://Models/Final Models/Tower/FtrAntiqueDresser/FtrAntiqueDresser.tscn",
	"res://Models/Final Models/Tower/FtrElegantTableM/Textures/FtrElegantTableM_icon.png": "res://Models/Final Models/Tower/FtrElegantTableM/FtrElegantTableM.tscn",
	"res://Models/Final Models/Tower/FtrPartitionDesk/Textures/FtrPartitionDesk_icon.png": "res://Models/Final Models/Tower/FtrPartitionDesk/FtrPartitionDesk.tscn",
	"res://Models/Final Models/Tower/FtrElegantChairS/Textures/FtrElegantChairS_icon.png": "res://Models/Final Models/Tower/FtrElegantChairS/FtrElegantChairS.tscn",
	"res://Models/Final Models/Bedrooms/FtrAntiqueClock/Textures/FtrAntiqueClock_icon.png": "res://Models/Final Models/Bedrooms/FtrAntiqueClock/FtrAntiqueClock.tscn",
	"res://Models/Final Models/Tower/FtrDrawingTable/Textures/FtrDrawingTable_icon.png": "res://Models/Final Models/Tower/FtrDrawingTable/FtrDrawingTable.tscn",
	"res://Models/Final Models/Tower/FtrLamp/Textures/FtrLamp_icon.png": "res://Models/Final Models/Tower/FtrLamp/FtrLamp.tscn",
	"res://Models/Final Models/Tower/FtrLogSofaS/Textures/FtrLogSofaS_icon.png": "res://Models/Final Models/Tower/FtrLogSofaS/FtrLogSofaS.tscn",
	"res://Models/Final Models/Tower/FtrOpenshelfWood/Textures/FtrOpenshelfWood_icon.png": "res://Models/Final Models/Tower/FtrOpenshelfWood/FtrOpenshelfWood.tscn",
	"res://Models/Final Models/Tower/FtrPianochair/Textures/FtrPianochair_icon.png": "res://Models/Final Models/Tower/FtrPianochair/FtrPianochair.tscn",
	"res://Models/Final Models/Tower/FtrPianoUpright/Textures/FtrPianoUpright_icon.png": "res://Models/Final Models/Tower/FtrPianoUpright/FtrPianoUpright.tscn",
	"res://Models/Final Models/Tower/FtrLogSofaL/Textures/FtrLogSofaL_icon.png": "res://Models/Final Models/Tower/FtrLogSofaL/FtrLogSofaL.tscn",
	"res://Models/Final Models/Tower/FtrRockingchair/Textures/FtrRockingchair_icon.png": "res://Models/Final Models/Tower/FtrRockingchair/FtrRockingchair.tscn",
	"res://Models/Final Models/Tower/FtrSimpleDresser/Textures/FtrSimpleDresser_icon.png": "res://Models/Final Models/Tower/FtrSimpleDresser/FtrSimpleDresser.tscn",
	"res://Models/Final Models/Tower/FtrBookshelf/Textures/FtrBookshelf_icon.png": "res://Models/Final Models/Tower/FtrBookshelf/FtrBookshelf.tscn",
	"res://Models/Final Models/Tower/FtrBlockShelf/Textures/FtrBlockShelf_icon.png": "res://Models/Final Models/Tower/FtrBlockShelf/FtrBlockShelf.tscn",
	"res://Models/Final Models/Tower/FtrStudyDesk/Textures/FtrStudyDesk_icon.png": "res://Models/Final Models/Tower/FtrStudyDesk/FtrStudyDesk.tscn",
	"res://Models/Final Models/Tower/FtrStudyChair/Textures/FtrStudyChair_icon.png": "res://Models/Final Models/Tower/FtrStudyChair/FtrStudyChair.tscn",
	"res://Models/Final Models/Tower/FtrWoodenTableS/Textures/FtrWoodenTableS_icon.png": "res://Models/Final Models/Tower/FtrWoodenTableS/FtrWoodenTableS.tscn",
	"res://Models/Final Models/Tower/FtrFloorchair/Textures/FtrFloorchair_icon.png": "res://Models/Final Models/Tower/FtrFloorchair/FtrFloorchair.tscn",
	"res://Models/Final Models/Tower/FtrLaptop/Textures/FtrLaptop_icon.png": "res://Models/Final Models/Tower/FtrLaptop/FtrLaptop.tscn",
	"res://Models/Final Models/Tower/FtrPianoGrand/Textures/FtrPianoGrand_icon.png": "res://Models/Final Models/Tower/FtrPianoGrand/FtrPianoGrand.tscn",
	"res://Models/Final Models/Tower/FtrElegantSofaL/Textures/FtrElegantSofaL_icon.png": "res://Models/Final Models/Tower/FtrElegantSofaL/FtrElegantSofaL.tscn",
	"res://Models/Final Models/Tower/FtrSofaL/Textures/FtrSofaL_icon.png": "res://Models/Final Models/Tower/FtrSofaL/FtrSofaL.tscn",
	"res://Models/Final Models/Tower/FtrMomCushion/Textures/FtrMomCushion_icon.png": "res://Models/Final Models/Tower/FtrMomCushion/FtrMomCushion.tscn",
	"res://Models/Final Models/Tower/FtrCountryChairS/Textures/FtrCountryChairS_icon.png": "res://Models/Final Models/Tower/FtrCountryChairS/FtrCountryChairS.tscn",
	"res://Models/Final Models/Tower/FtrRattanChairS/Textures/FtrRattanChairS_icon.png": "res://Models/Final Models/Tower/FtrRattanChairS/FtrRattanChairS.tscn",
	"res://Models/Final Models/Downstairs/FtrCushionJapan/Textures/FtrCushionJapan_icon.png": "res://Models/Final Models/Downstairs/FtrCushionJapan/FtrCushionJapan.tscn",
	"res://Models/Final Models/Downstairs/FtrCushionJapanPile/Textures/FtrCushionJapanPile_icon.png": "res://Models/Final Models/Downstairs/FtrCushionJapanPile/FtrCushionJapanPile.tscn",
	"res://Models/Final Models/Downstairs/FtrColorBoxShelfSide/Textures/FtrColorBoxShelfSide_icon.png": "res://Models/Final Models/Downstairs/FtrColorBoxShelfSide/FtrColorBoxShelfSide.tscn",
	"res://Models/Final Models/Downstairs/FtrRailroad/Textures/FtrRailroad_icon.png": "res://Models/Final Models/Downstairs/FtrRailroad/FtrRailroad.tscn",
	
	#Rugs
	"res://Models/Final Models/Rugs/RugOtherCountryS00/Textures/RugOtherCountry_icon.png" : "res://Models/Final Models/Rugs/RugOtherCountryS00/RugOtherCountryS00.tscn",
	"res://Models/Final Models/Rugs/RugRectArgyleL01/Textures/RugRectArgyleL01_icon.png" : "res://Models/Final Models/Rugs/RugRectArgyleL01/RugRectArgyleL01.tscn",
	"res://Models/Final Models/Rugs/RugRectBathmatS00/Textures/RugRectBathmatS00_icon.png": "res://Models/Final Models/Rugs/RugRectBathmatS00/RugRectBathmatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectBorderL00/Textures/RugRectBorderL00_icon.png": "res://Models/Final Models/Rugs/RugRectBorderL00/RugRectBorderL00.tscn",
	"res://Models/Final Models/Rugs/RugRectBotanicalL00/Textures/RugRectBotanicalL00_icon.png" :"res://Models/Final Models/Rugs/RugRectBotanicalL00/RugRectBotanicalL00.tscn",
	"res://Models/Final Models/Rugs/RugRectChinamatS00/Textures/RugRectChinamatS00_icon.png" : "res://Models/Final Models/Rugs/RugRectChinamatS00/RugRectChinamatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDoormatS00/Textures/RugRectDoormatS00_icon.png" : "res://Models/Final Models/Rugs/RugRectDoormatS00/RugRectDoormatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDotL00/Textures/RugRectDotL00_icon.png" : "res://Models/Final Models/Rugs/RugRectDotL00/RugRectDotL00.tscn",
	"res://Models/Final Models/Rugs/RugRectElegantM00/Textures/RugRectElegantM00_icon.png" : "res://Models/Final Models/Rugs/RugRectElegantM00/RugRectElegantM00.tscn",
	"res://Models/Final Models/Rugs/RugRectEntranceS00/Textures/RugRectEntranceS00_icon.png" : "res://Models/Final Models/Rugs/RugRectEntranceS00/RugRectEntranceS00.tscn",
	"res://Models/Final Models/Rugs/RugRectJuneBrideM00/Textures/RugRectJuneBrideM00_icon.png" : "res://Models/Final Models/Rugs/RugRectJuneBrideM00/RugRectJuneBrideM00.tscn",
	"res://Models/Final Models/Rugs/RugRectKitchenS00/Textures/RugRectKitchenS00_icon.png" : "res://Models/Final Models/Rugs/RugRectKitchenS00/RugRectKitchenS00.tscn",
	#"res://Models/Final Models/Rugs/RugRectPatternS00/Textures/RugRectPatternS00_icon.png" : "res://Models/Final Models/Rugs/RugRectPatternS00/RugRectPatternS00.tscn",
	"res://Models/Final Models/Rugs/RugRectPiratesM00/Textures/RugRectPiratesM00_icon.png" : "res://Models/Final Models/Rugs/RugRectPiratesM00/RugRectPiratesM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundLaceM00/Textures/RugRoundLaceM00_icon.png" : "res://Models/Final Models/Rugs/RugRoundLaceM00/RugRoundLaceM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleM00/Textures/RugRoundSimpleM00_icon.png" : "res://Models/Final Models/Rugs/RugRoundSimpleM00/RugRoundSimpleM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleS00/Textures/RugRoundSimpleS00_icon.png" : "res://Models/Final Models/Rugs/RugRoundSimpleS00/RugRoundSimpleS00.tscn",
	#"res://Models/Final Models/Rugs/RugSquareChristmasL00/Textures/RugSquareChristmasL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareChristmasL00/RugSquareChristmasL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareElegantL00/Textures/RugSquareElegantL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareElegantL00/RugSquareElegantL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHalloweenL00/Textures/RugSquareHalloweenL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHalloweenL00/RugSquareHalloweenL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHarvestL00/Textures/RugSquareHarvestL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHarvestL00/RugSquareHarvestL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHawaiianL00/Textures/RugSquareHawaiianL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHawaiianL00/RugSquareHawaiianL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareKirimL00/Textures/RugSquareKirimL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareKirimL00/RugSquareKirimL00.tscn",
	#"res://Models/Final Models/Rugs/RugSquarePatternL00/Textures/mMaRugSquarePatternL00_icon.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquarePersianL01/Textures/RugSquarePersianL01_icon.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleM01/Textures/RugSquareSimpleM01_icon.png" : "res://Models/Final Models/Rugs/RugSquareSimpleM01/RugSquareSimpleM01.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleS01/Textures/RugSquareSimpleS01_icon.png" : "res://Models/Final Models/Rugs/RugSquareSimpleS01/RugSquareSimpleS01.tscn",
}
