extends Resource
class_name OfficeFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Office/FtrWorkbenchIronwood/Textures/FtrWorkbenchIronwood_icon.png": preload("res://Models/Final Models/Office/FtrWorkbenchIronwood/FtrWorkbenchIronwood.tscn"),
	"res://Models/Final Models/Office/FtrCartoonistset/Textures/FtrCartoonistset_icon.png": preload("res://Models/Final Models/Office/FtrCartoonistset/FtrCartoonistset.tscn"),
	"res://Models/Final Models/Office/FtrCopy/Textures/FtrCopy_icon.png": preload("res://Models/Final Models/Office/FtrCopy/FtrCopy.tscn"),
	"res://Models/Final Models/Office/FtrGamingChair/Textures/FtrGamingChair_icon.png": preload("res://Models/Final Models/Office/FtrGamingChair/FtrGamingChair.tscn"),
	"res://Models/Final Models/Office/FtrOfficeCabinet/Textures/FtrOfficeCabinet_icon.png": preload("res://Models/Final Models/Office/FtrOfficeCabinet/FtrOfficeCabinet.tscn"),
	"res://Models/Final Models/Office/FtrOfficeChair/Textures/FtrOfficeChair_icon.png": preload("res://Models/Final Models/Office/FtrOfficeChair/FtrOfficeChair.tscn"),
	"res://Models/Final Models/Office/FtrGamingDesk/Textures/FtrGamingDesk_icon.png": preload("res://Models/Final Models/Office/FtrGamingDesk/FtrGamingDesk.tscn"),
	"res://Models/Final Models/Office/FtrOfficeTable/Textures/FtrOfficeTable_icon.png": preload("res://Models/Final Models/Office/FtrOfficeTable/FtrOfficeTable.tscn"),
	"res://Models/Final Models/Office/FtrFilecabinetM/Textures/FtrFilecabinetM_icon.png": preload("res://Models/Final Models/Office/FtrFilecabinetM/FtrFilecabinetM.tscn"),
	"res://Models/Final Models/Office/FtrOfficeTableRetro/Textures/FtrOfficeTableRetro_icon.png": preload("res://Models/Final Models/Office/FtrOfficeTableRetro/FtrOfficeTableRetro.tscn"),
	"res://Models/Final Models/Office/FtrFilecabinetL/Textures/FtrFilecabinetL_icon.png": preload("res://Models/Final Models/Office/FtrFilecabinetL/FtrFilecabinetL.tscn"),
	"res://Models/Final Models/Office/FtrWhiteboard/Textures/FtrWhiteboard_icon.png": preload("res://Models/Final Models/Office/FtrWhiteboard/FtrWhiteboard.tscn"),
	"res://Models/Final Models/Office/FtrClipboard/Textures/FtrClipboard_icon.png": preload("res://Models/Final Models/Office/FtrClipboard/FtrClipboard.tscn"),
	"res://Models/Final Models/Office/FtrDesktopPC/Textures/FtrDesktopPC_icon.png": preload("res://Models/Final Models/Office/FtrDesktopPC/FtrDesktopPC.tscn"),
	"res://Models/Final Models/Office/FtrHumidifier/Textures/FtrHumidifier_icon.png": preload("res://Models/Final Models/Office/FtrHumidifier/FtrHumidifier.tscn"),
	"res://Models/Final Models/Office/FtrTablet/Textures/FtrTablet_icon.png": preload("res://Models/Final Models/Office/FtrTablet/FtrTablet.tscn"),
	"res://Models/Final Models/Office/FtrDocument/Textures/FtrDocument_icon.png": preload("res://Models/Final Models/Office/FtrDocument/FtrDocument.tscn"),
	"res://Models/Final Models/Office/FtrCorkboard/Textures/FtrCorkboard_icon.png": preload("res://Models/Final Models/Office/FtrCorkboard/FtrCorkboard.tscn"),
	"res://Models/Final Models/Office/FtrPlantAnthurium/Textures/FtrPlantAnthurium_icon.png": preload("res://Models/Final Models/Office/FtrPlantAnthurium/FtrPlantAnthurium.tscn"),
	"res://Models/Final Models/Office/FtrBonsaiShelf/Textures/FtrBonsaiShelf_icon.png": preload("res://Models/Final Models/Office/FtrBonsaiShelf/FtrBonsaiShelf.tscn"),
	"res://Models/Final Models/Office/FtrCatgrass/Textures/FtrCatgrass_icon.png": preload("res://Models/Final Models/Office/FtrCatgrass/FtrCatgrass.tscn"),
	"res://Models/Final Models/Office/FtrPlantGoldcrest/Textures/FtrPlantGoldcrest_icon.png": preload("res://Models/Final Models/Office/FtrPlantGoldcrest/FtrPlantGoldcrest.tscn"),
	"res://Models/Final Models/Office/FtrPlantYamadoriyashi/Textures/FtrPlantYamadoriyashi_icon.png": preload("res://Models/Final Models/Office/FtrPlantYamadoriyashi/FtrPlantYamadoriyashi.tscn"),
	"res://Models/Final Models/Office/FtrPlantMonstera/Textures/FtrPlantMonstera_icon.png": preload("res://Models/Final Models/Office/FtrPlantMonstera/FtrPlantMonstera.tscn"),
	"res://Models/Final Models/Office/FtrPlantTakumi/Textures/FtrPlantTakumi_icon.png": preload("res://Models/Final Models/Office/FtrPlantTakumi/FtrPlantTakumi.tscn"),
	"res://Models/Final Models/Office/FtrPlantSucculents/Textures/FtrPlantSucculents_icon.png": preload("res://Models/Final Models/Office/FtrPlantSucculents/FtrPlantSucculents.tscn"),
	"res://Models/Final Models/Office/FtrPlantWall/Textures/FtrPlantWall_icon.png": preload("res://Models/Final Models/Office/FtrPlantWall/FtrPlantWall.tscn"),
	"res://Models/Final Models/Office/FtrLampMount/Textures/FtrLampMount_icon.png": preload("res://Models/Final Models/Office/FtrLampMount/FtrLampMount.tscn"),
}
