extends Resource
class_name OfficeFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Office/FtrWorkbenchIronwood/Textures/FtrWorkbenchIronwood_icon.png": "res://Models/Final Models/Office/FtrWorkbenchIronwood/FtrWorkbenchIronwood.tscn",
	"res://Models/Final Models/Office/FtrCopy/Textures/FtrCopy_icon.png": "res://Models/Final Models/Office/FtrCopy/FtrCopy.tscn",
	"res://Models/Final Models/Office/FtrGamingChair/Textures/FtrGamingChair_icon.png": "res://Models/Final Models/Office/FtrGamingChair/FtrGamingChair.tscn",
	"res://Models/Final Models/Office/FtrOfficeCabinet/Textures/FtrOfficeCabinet_icon.png": "res://Models/Final Models/Office/FtrOfficeCabinet/FtrOfficeCabinet.tscn",
	"res://Models/Final Models/Office/FtrOfficeChair/Textures/FtrOfficeChair_icon.png": "res://Models/Final Models/Office/FtrOfficeChair/FtrOfficeChair.tscn",
	"res://Models/Final Models/Office/FtrGamingDesk/Textures/FtrGamingDesk_icon.png": "res://Models/Final Models/Office/FtrGamingDesk/FtrGamingDesk.tscn",
	#"res://Models/Final Models/Office/FtrOfficeTable/Textures/FtrOfficeTable_icon.png": "res://Models/Final Models/Office/FtrOfficeTable/FtrOfficeTable.tscn",
	"res://Models/Final Models/Office/FtrFilecabinetM/Textures/FtrFilecabinetM_icon.png": "res://Models/Final Models/Office/FtrFilecabinetM/FtrFilecabinetM.tscn",
	"res://Models/Final Models/Office/FtrOfficeTableRetro/Textures/FtrOfficeTableRetro_icon.png": "res://Models/Final Models/Office/FtrOfficeTableRetro/FtrOfficeTableRetro.tscn",
	"res://Models/Final Models/Office/FtrFilecabinetL/Textures/FtrFilecabinetL_icon.png": "res://Models/Final Models/Office/FtrFilecabinetL/FtrFilecabinetL.tscn",
	"res://Models/Final Models/Office/FtrWhiteboard/Textures/FtrWhiteboard_icon.png": "res://Models/Final Models/Office/FtrWhiteboard/FtrWhiteboard.tscn",
	"res://Models/Final Models/Office/FtrBonsaiShelf/Textures/FtrBonsaiShelf_icon.png": "res://Models/Final Models/Office/FtrBonsaiShelf/FtrBonsaiShelf.tscn",
	"res://Models/Final Models/Office/FtrLampMount/Textures/FtrLampMount_icon.png": "res://Models/Final Models/Office/FtrLampMount/FtrLampMount.tscn",
	
	#Rugs+
	"res://Models/Final Models/Rugs/RugOtherCountryS00/Textures/RugOtherCountry_icon.png" : "res://Models/Final Models/Rugs/RugOtherCountryS00/RugOtherCountryS00.tscn",
	"res://Models/Final Models/Rugs/RugRectArgyleL01/Textures/RugRectArgyleL01_icon.png" : "res://Models/Final Models/Rugs/RugRectArgyleL01/RugRectArgyleL01.tscn",
	"res://Models/Final Models/Rugs/RugRectBathmatS00/Textures/RugRectBathmatS00_icon.png": "res://Models/Final Models/Rugs/RugRectBathmatS00/RugRectBathmatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectBorderL00/Textures/RugRectBorderL00_icon.png": "res://Models/Final Models/Rugs/RugRectBorderL00/RugRectBorderL00.tscn",
	"res://Models/Final Models/Rugs/RugRectBotanicalL00/Textures/RugRectBotanicalL00_icon.png" :"res://Models/Final Models/Rugs/RugRectBotanicalL00/RugRectBotanicalL00.tscn",
	"res://Models/Final Models/Rugs/RugRectChinamatS00/Textures/RugRectChinamatS00_icon.png" : "res://Models/Final Models/Rugs/RugRectChinamatS00/RugRectChinamatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDoormatS00/Textures/RugRectDoormatS00_icon.png" : "res://Models/Final Models/Rugs/RugRectDoormatS00/RugRectDoormatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDotL00/Textures/RugRectDotL00_icon.png" : "res://Models/Final Models/Rugs/RugRectDotL00/RugRectDotL00.tscn",
	"res://Models/Final Models/Rugs/RugRectElegantM00/Textures/RugRectElegantM00_icon.png" : "res://Models/Final Models/Rugs/RugRectElegantM00/RugRectElegantM00.tscn",
	"res://Models/Final Models/Rugs/RugRectEntranceS00/Textures/RugRectEntranceS00_icon.png" : "res://Models/Final Models/Rugs/RugRectEntranceS00/RugRectEntranceS00.tscn",
	"res://Models/Final Models/Rugs/RugRectJuneBrideM00/Textures/RugRectJuneBrideM00_icon.png" : "res://Models/Final Models/Rugs/RugRectJuneBrideM00/RugRectJuneBrideM00.tscn",
	"res://Models/Final Models/Rugs/RugRectKitchenS00/Textures/RugRectKitchenS00_icon.png" : "res://Models/Final Models/Rugs/RugRectKitchenS00/RugRectKitchenS00.tscn",
	#"res://Models/Final Models/Rugs/RugRectPatternS00/Textures/RugRectPatternS00_icon.png" : "res://Models/Final Models/Rugs/RugRectPatternS00/RugRectPatternS00.tscn",
	"res://Models/Final Models/Rugs/RugRectPiratesM00/Textures/RugRectPiratesM00_icon.png" : "res://Models/Final Models/Rugs/RugRectPiratesM00/RugRectPiratesM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundLaceM00/Textures/RugRoundLaceM00_icon.png" : "res://Models/Final Models/Rugs/RugRoundLaceM00/RugRoundLaceM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleM00/Textures/RugRoundSimpleM00_icon.png" : "res://Models/Final Models/Rugs/RugRoundSimpleM00/RugRoundSimpleM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleS00/Textures/RugRoundSimpleS00_icon.png" : "res://Models/Final Models/Rugs/RugRoundSimpleS00/RugRoundSimpleS00.tscn",
	#"res://Models/Final Models/Rugs/RugSquareChristmasL00/Textures/RugSquareChristmasL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareChristmasL00/RugSquareChristmasL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareElegantL00/Textures/RugSquareElegantL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareElegantL00/RugSquareElegantL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHalloweenL00/Textures/RugSquareHalloweenL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHalloweenL00/RugSquareHalloweenL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHarvestL00/Textures/RugSquareHarvestL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHarvestL00/RugSquareHarvestL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHawaiianL00/Textures/RugSquareHawaiianL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHawaiianL00/RugSquareHawaiianL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareKirimL00/Textures/RugSquareKirimL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareKirimL00/RugSquareKirimL00.tscn",
	#"res://Models/Final Models/Rugs/RugSquarePatternL00/Textures/mMaRugSquarePatternL00_icon.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquarePersianL01/Textures/RugSquarePersianL01_icon.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleM01/Textures/RugSquareSimpleM01_icon.png" : "res://Models/Final Models/Rugs/RugSquareSimpleM01/RugSquareSimpleM01.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleS01/Textures/RugSquareSimpleS01_icon.png" : "res://Models/Final Models/Rugs/RugSquareSimpleS01/RugSquareSimpleS01.tscn",
	
}
