extends Resource
class_name BathroomFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Bathrooms/FtrBathchair/Textures/FtrBathchair_icon.png": "res://Models/Final Models/Bathrooms/FtrBathchair/FtrBathchair.tscn",
	#textures are fricked might replace "res://Models/Final Models/Bathrooms/FtrWashstand/Textures/FtrWashstand_icon.png": "res://Models/Final Models/Bathrooms/FtrWashstand/FtrWashstand.tscn",
	"res://Models/Final Models/Bathrooms/FtrBathtubCabriole/Textures/FtrBathtubCabriole_icon.png": "res://Models/Final Models/Bathrooms/FtrBathtubCabriole/FtrBathtubCabriole.tscn",
	"res://Models/Final Models/Bathrooms/FtrWeightscale/Textures/FtrWeightscale_icon.png": "res://Models/Final Models/Bathrooms/FtrWeightscale/FtrWeightscale.tscn",
	"res://Models/Final Models/Bathrooms/FtrWashstandGrace/Textures/FtrWashstandGrace_icon.png": "res://Models/Final Models/Bathrooms/FtrWashstandGrace/FtrWashstandGrace.tscn",
	#textures are fricked "res://Models/Final Models/Bathrooms/FtrBathtub/Textures/FtrBathtub_icon.png": "res://Models/Final Models/Bathrooms/FtrBathtub/FtrBathtub.tscn",
	"res://Models/Final Models/Bathrooms/FtrWashstandBowl/Textures/FtrWashstandBowl_icon.png": "res://Models/Final Models/Bathrooms/FtrWashstandBowl/FtrWashstandBowl.tscn",
	"res://Models/Final Models/Bathrooms/FtrPlasticChest/Textures/FtrPlasticChest_icon.png": "res://Models/Final Models/Bathrooms/FtrPlasticChest/FtrPlasticChest.tscn",
	"res://Models/Final Models/Bathrooms/FtrShowerboothSquare/Textures/FtrShowerboothSquare_icon.png": "res://Models/Final Models/Bathrooms/FtrShowerboothSquare/FtrShowerboothSquare.tscn",
	"res://Models/Final Models/Bathrooms/FtrSimpleDresser/Textures/FtrSimpleDresser_icon.png": "res://Models/Final Models/Bathrooms/FtrSimpleDresser/FtrSimpleDresser.tscn",
	"res://Models/Final Models/Bathrooms/FtrWCTankless/Textures/FtrWCTankless_icon.png": "res://Models/Final Models/Bathrooms/FtrWCTankless/FtrWCTankless.tscn",
	"res://Models/Final Models/Bathrooms/FtrWC/Textures/FtrWC_icon.png": "res://Models/Final Models/Bathrooms/FtrWC/FtrWC.tscn",
	"res://Models/Final Models/Bathrooms/FtrCleaningsetWC/Textures/FtrCleaningsetWC_icon.png": "res://Models/Final Models/Bathrooms/FtrCleaningsetWC/FtrCleaningsetWC.tscn",
	#textures are fricked "res://Models/Final Models/Bathrooms/FtrGardenTable/Textures/FtrGardenTable_icon.png": "res://Models/Final Models/Bathrooms/FtrGardenTable/FtrGardenTable.tscn",
	"res://Models/Final Models/Bathrooms/FtrRattanTrashbox/Textures/FtrRattanTrashbox_icon.png": "res://Models/Final Models/Bathrooms/FtrRattanTrashbox/FtrRattanTrashbox.tscn",
	"res://Models/Final Models/Bathrooms/FtrTrashboxWood/Textures/FtrTrashboxWood_icon.png": "res://Models/Final Models/Bathrooms/FtrTrashboxWood/FtrTrashboxWood.tscn",
	"res://Models/Final Models/Bathrooms/FtrElegantMirror/Textures/FtrElegantMirror_icon.png": "res://Models/Final Models/Bathrooms/FtrElegantMirror/FtrElegantMirror.tscn",
	"res://Models/Final Models/Bathrooms/FtrElegantTableM/Textures/FtrElegantTableM_icon.png": "res://Models/Final Models/Bathrooms/FtrElegantTableM/FtrElegantTableM.tscn",
	
		#Rugs
	"res://Models/Final Models/Rugs/RugOtherCountryS00/Textures/RugOtherCountry_icon.png" : "res://Models/Final Models/Rugs/RugOtherCountryS00/RugOtherCountryS00.tscn",
	"res://Models/Final Models/Rugs/RugRectArgyleL01/Textures/RugRectArgyleL01_icon.png" : "res://Models/Final Models/Rugs/RugRectArgyleL01/RugRectArgyleL01.tscn",
	"res://Models/Final Models/Rugs/RugRectBathmatS00/Textures/RugRectBathmatS00_icon.png": "res://Models/Final Models/Rugs/RugRectBathmatS00/RugRectBathmatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectBorderL00/Textures/RugRectBorderL00_icon.png": "res://Models/Final Models/Rugs/RugRectBorderL00/RugRectBorderL00.tscn",
	"res://Models/Final Models/Rugs/RugRectBotanicalL00/Textures/RugRectBotanicalL00_icon.png" :"res://Models/Final Models/Rugs/RugRectBotanicalL00/RugRectBotanicalL00.tscn",
	"res://Models/Final Models/Rugs/RugRectChinamatS00/Textures/RugRectChinamatS00_icon.png" : "res://Models/Final Models/Rugs/RugRectChinamatS00/RugRectChinamatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDoormatS00/Textures/RugRectDoormatS00_icon.png" : "res://Models/Final Models/Rugs/RugRectDoormatS00/RugRectDoormatS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDotL00/Textures/RugRectDotL00_icon.png" : "res://Models/Final Models/Rugs/RugRectDotL00/RugRectDotL00.tscn",
	"res://Models/Final Models/Rugs/RugRectElegantM00/Textures/RugRectElegantM00_icon.png" : "res://Models/Final Models/Rugs/RugRectElegantM00/RugRectElegantM00.tscn",
	"res://Models/Final Models/Rugs/RugRectEntranceS00/Textures/RugRectEntranceS00_icon.png" : "res://Models/Final Models/Rugs/RugRectEntranceS00/RugRectEntranceS00.tscn",
	"res://Models/Final Models/Rugs/RugRectJuneBrideM00/Textures/RugRectJuneBrideM00_icon.png" : "res://Models/Final Models/Rugs/RugRectJuneBrideM00/RugRectJuneBrideM00.tscn",
	"res://Models/Final Models/Rugs/RugRectKitchenS00/Textures/RugRectKitchenS00_icon.png" : "res://Models/Final Models/Rugs/RugRectKitchenS00/RugRectKitchenS00.tscn",
	#"res://Models/Final Models/Rugs/RugRectPatternS00/Textures/RugRectPatternS00_icon.png" : "res://Models/Final Models/Rugs/RugRectPatternS00/RugRectPatternS00.tscn",
	"res://Models/Final Models/Rugs/RugRectPiratesM00/Textures/RugRectPiratesM00_icon.png" : "res://Models/Final Models/Rugs/RugRectPiratesM00/RugRectPiratesM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundLaceM00/Textures/RugRoundLaceM00_icon.png" : "res://Models/Final Models/Rugs/RugRoundLaceM00/RugRoundLaceM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleM00/Textures/RugRoundSimpleM00_icon.png" : "res://Models/Final Models/Rugs/RugRoundSimpleM00/RugRoundSimpleM00.tscn",
	"res://Models/Final Models/Rugs/RugRoundSimpleS00/Textures/RugRoundSimpleS00_icon.png" : "res://Models/Final Models/Rugs/RugRoundSimpleS00/RugRoundSimpleS00.tscn",
	#"res://Models/Final Models/Rugs/RugSquareChristmasL00/Textures/RugSquareChristmasL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareChristmasL00/RugSquareChristmasL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareElegantL00/Textures/RugSquareElegantL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareElegantL00/RugSquareElegantL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHalloweenL00/Textures/RugSquareHalloweenL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHalloweenL00/RugSquareHalloweenL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHarvestL00/Textures/RugSquareHarvestL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHarvestL00/RugSquareHarvestL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareHawaiianL00/Textures/RugSquareHawaiianL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareHawaiianL00/RugSquareHawaiianL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareKirimL00/Textures/RugSquareKirimL00_icon.png" : "res://Models/Final Models/Rugs/RugSquareKirimL00/RugSquareKirimL00.tscn",
	#"res://Models/Final Models/Rugs/RugSquarePatternL00/Textures/mMaRugSquarePatternL00_icon.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquarePersianL01/Textures/RugSquarePersianL01_icon.png" : "res://Models/Final Models/Rugs/RugSquarePatternL00/RugSquarePatternL00.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleM01/Textures/RugSquareSimpleM01_icon.png" : "res://Models/Final Models/Rugs/RugSquareSimpleM01/RugSquareSimpleM01.tscn",
	"res://Models/Final Models/Rugs/RugSquareSimpleS01/Textures/RugSquareSimpleS01_icon.png" : "res://Models/Final Models/Rugs/RugSquareSimpleS01/RugSquareSimpleS01.tscn",
}
