extends Resource
class_name BathroomFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Bathrooms/FtrBathchair/Textures/FtrBathchair_icon.png": preload("res://Models/Final Models/Bathrooms/FtrBathchair/FtrBathchair.tscn"),
	"res://Models/Final Models/Bathrooms/FtrWashstand/Textures/FtrWashstand_icon.png": preload("res://Models/Final Models/Bathrooms/FtrWashstand/FtrWashstand.tscn"),
	"res://Models/Final Models/Bathrooms/FtrBathtubCabriole/Textures/FtrBathtubCabriole_icon.png": preload("res://Models/Final Models/Bathrooms/FtrBathtubCabriole/FtrBathtubCabriole.tscn"),
	"res://Models/Final Models/Bathrooms/FtrWeightscale/Textures/FtrWeightscale_icon.png": preload("res://Models/Final Models/Bathrooms/FtrWeightscale/FtrWeightscale.tscn"),
	"res://Models/Final Models/Bathrooms/FtrWashstandGrace/Textures/FtrWashstandGrace_icon.png": preload("res://Models/Final Models/Bathrooms/FtrWashstandGrace/FtrWashstandGrace.tscn"),
	"res://Models/Final Models/Bathrooms/FtrBathtub/Textures/FtrBathtub_icon.png": preload("res://Models/Final Models/Bathrooms/FtrBathtub/FtrBathtub.tscn"),
	"res://Models/Final Models/Bathrooms/FtrWashstandBowl/Textures/FtrWashstandBowl_icon.png": preload("res://Models/Final Models/Bathrooms/FtrWashstandBowl/FtrWashstandBowl.tscn"),
	"res://Models/Final Models/Bathrooms/FtrPlasticChest/Textures/FtrPlasticChest_icon.png": preload("res://Models/Final Models/Bathrooms/FtrPlasticChest/FtrPlasticChest.tscn"),
	"res://Models/Final Models/Bathrooms/FtrShowerboothSquare/Textures/FtrShowerboothSquare_icon.png": preload("res://Models/Final Models/Bathrooms/FtrShowerboothSquare/FtrShowerboothSquare.tscn"),
	"res://Models/Final Models/Bathrooms/FtrSimpleDresser/Textures/FtrSimpleDresser_icon.png": preload("res://Models/Final Models/Bathrooms/FtrSimpleDresser/FtrSimpleDresser.tscn"),
	"res://Models/Final Models/Bathrooms/FtrWCTankless/Textures/FtrWCTankless_icon.png": preload("res://Models/Final Models/Bathrooms/FtrWCTankless/FtrWCTankless.tscn"),
	"res://Models/Final Models/Bathrooms/FtrWC/Textures/FtrWC_icon.png": preload("res://Models/Final Models/Bathrooms/FtrWC/FtrWC.tscn"),
	"res://Models/Final Models/Bathrooms/FtrCleaningsetWC/Textures/FtrCleaningsetWC_icon.png": preload("res://Models/Final Models/Bathrooms/FtrCleaningsetWC/FtrCleaningsetWC.tscn"),
	"res://Models/Final Models/Bathrooms/FtrBottleShampoo/Textures/FtrBottleShampoo_icon.png": preload("res://Models/Final Models/Bathrooms/FtrBottleShampoo/FtrBottleShampoo.tscn"),
	"res://Models/Final Models/Bathrooms/FtrRattanBasket/Textures/FtrRattanBasket_icon.png": preload("res://Models/Final Models/Bathrooms/FtrRattanBasket/FtrRattanBasket.tscn"),
	"res://Models/Final Models/Bathrooms/FtrTowelrackWall/Textures/FtrTowelrackWall_icon.png": preload("res://Models/Final Models/Bathrooms/FtrTowelrackWall/FtrTowelrackWall.tscn"),
	"res://Models/Final Models/Bathrooms/FtrShowerWall/Textures/FtrShowerWall_icon.png": preload("res://Models/Final Models/Bathrooms/FtrShowerWall/FtrShowerWall.tscn"),
	"res://Models/Final Models/Bathrooms/FtrGardenTable/Textures/FtrGardenTable_icon.png": preload("res://Models/Final Models/Bathrooms/FtrGardenTable/FtrGardenTable.tscn"),
	"res://Models/Final Models/Bathrooms/FtrToothbrush/Textures/FtrToothbrush_icon.png": preload("res://Models/Final Models/Bathrooms/FtrToothbrush/FtrToothbrush.tscn"),
	"res://Models/Final Models/Bathrooms/FtrMacrametapestry/Textures/FtrMacrametapestry_icon.png": preload("res://Models/Final Models/Bathrooms/FtrMacrametapestry/FtrMacrametapestry.tscn"),
	"res://Models/Final Models/Bathrooms/FtrRattanTrashbox/Textures/FtrRattanTrashbox_icon.png": preload("res://Models/Final Models/Bathrooms/FtrRattanTrashbox/FtrRattanTrashbox.tscn"),
	"res://Models/Final Models/Bathrooms/FtrWoodenMirror/Textures/FtrWoodenMirror_icon.png": preload("res://Models/Final Models/Bathrooms/FtrWoodenMirror/FtrWoodenMirror.tscn"),
	"res://Models/Final Models/Bathrooms/FtrTrashboxWood/Textures/FtrTrashboxWood_icon.png": preload("res://Models/Final Models/Bathrooms/FtrTrashboxWood/FtrTrashboxWood.tscn"),
	"res://Models/Final Models/Bathrooms/FtrElegantMirror/Textures/FtrElegantMirror_icon.png": preload("res://Models/Final Models/Bathrooms/FtrElegantMirror/FtrElegantMirror.tscn"),
	"res://Models/Final Models/Bathrooms/FtrElegantTableM/Textures/FtrElegantTableM_icon.png": preload("res://Models/Final Models/Bathrooms/FtrElegantTableM/FtrElegantTableM.tscn"),
}
