extends Resource
class_name BackyardFurnitureInventory

@export var objects := {
	"res://Models/Final Models/Backyard/FtrBirdhouse/Textures/FtrBirdhouse_icon.png": "res://Models/Final Models/Backyard/FtrBirdhouse/FtrBirdhouse.tscn",
	"res://Models/Final Models/Backyard/FtrWellBrick/Textures/FtrWellBrick_icon.png": "res://Models/Final Models/Backyard/FtrWellBrick/FtrWellBrick.tscn",
	"res://Models/Final Models/Backyard/FtrStonewaterbowlSakura/Textures/FtrStonewaterbowlSakura_icon.png": "res://Models/Final Models/Backyard/FtrStonewaterbowlSakura/FtrStonewaterbowlSakura.tscn",
	"res://Models/Final Models/Backyard/FtrPottedPlant/Textures/FtrPottedPlant_icon.png": "res://Models/Final Models/Backyard/FtrPottedPlant/FtrPottedPlant.tscn",
	"res://Models/Final Models/Backyard/FtrGardenrockLow/Textures/FtrGardenrockLow_icon.png": "res://Models/Final Models/Backyard/FtrGardenrockLow/FtrGardenrockLow.tscn",
	"res://Models/Final Models/Backyard/FtrForsythia/Textures/FtrForsythia_icon.png": "res://Models/Final Models/Backyard/FtrForsythia/FtrForsythia.tscn",
	"res://Models/Final Models/Backyard/FtrGardenchair/Textures/FtrGardenchair_icon.png": "res://Models/Final Models/Backyard/FtrGardenchair/FtrGardenchair.tscn",
	"res://Models/Final Models/Backyard/FtrWaterview/Textures/FtrWaterview_icon.png": "res://Models/Final Models/Backyard/FtrWaterview/FtrWaterview.tscn",
	"res://Models/Final Models/Backyard/FtrLampGarden/Textures/FtrLampGarden_icon.png": "res://Models/Final Models/Backyard/FtrLampGarden/FtrLampGarden.tscn",
	"res://Models/Final Models/Backyard/FtrGardenrock/Textures/FtrGardenrock_icon.png": "res://Models/Final Models/Backyard/FtrGardenrock/FtrGardenrock.tscn",
	"res://Models/Final Models/Backyard/FtrGardenwagon/Textures/FtrGardenwagon_icon.png": "res://Models/Final Models/Backyard/FtrGardenwagon/FtrGardenwagon.tscn",
	"res://Models/Final Models/Backyard/FtrWesternGazebo/Textures/FtrWesternGazebo_icon.png": "res://Models/Final Models/Backyard/FtrWesternGazebo/FtrWesternGazebo.tscn",
	"res://Models/Final Models/Backyard/FtrPlantshelf/Textures/FtrPlantshelf_icon.png": "res://Models/Final Models/Backyard/FtrPlantshelf/FtrPlantshelf.tscn",
	"res://Models/Final Models/Backyard/FtrHandcart/Textures/FtrHandcart_icon.png": "res://Models/Final Models/Backyard/FtrHandcart/FtrHandcart.tscn",
	"res://Models/Final Models/Backyard/FtrHosereel/Textures/FtrHosereel_icon.png": "res://Models/Final Models/Backyard/FtrHosereel/FtrHosereel.tscn",
	"res://Models/Final Models/Backyard/FtrIrongardenBench/Textures/FtrIrongardenBench_icon.png": "res://Models/Final Models/Backyard/FtrIrongardenBench/FtrIrongardenBench.tscn",
	"res://Models/Final Models/Backyard/FtrIrongardenChair/Textures/FtrIrongardenChair_icon.png": "res://Models/Final Models/Backyard/FtrIrongardenChair/FtrIrongardenChair.tscn",
	"res://Models/Final Models/Backyard/FtrStonewaterbowlAutumun/Textures/FtrStonewaterbowlAutumun_icon.png": "res://Models/Final Models/Backyard/FtrStonewaterbowlAutumun/FtrStonewaterbowlAutumun.tscn",
	"res://Models/Final Models/Backyard/FtrGardenrockMoss/Textures/FtrGardenrockMoss_icon.png": "res://Models/Final Models/Backyard/FtrGardenrockMoss/FtrGardenrockMoss.tscn",
	"res://Models/Final Models/Backyard/FtrSakuraPicnicset/Textures/FtrSakuraPicnicset_icon.png": "res://Models/Final Models/Backyard/FtrSakuraPicnicset/FtrSakuraPicnicset.tscn",
	"res://Models/Final Models/Backyard/FtrWherearenOfficeHammock/Textures/FtrWherearenOfficeHammock_icon.png": "res://Models/Final Models/Backyard/FtrWherearenOfficeHammock/FtrWherearenOfficeHammock.tscn",
	"res://Models/Final Models/Backyard/FtrPergola/Textures/FtrPergola_icon.png": "res://Models/Final Models/Backyard/FtrPergola/FtrPergola.tscn",
	"res://Models/Final Models/Backyard/FtrGardenpool/Textures/FtrGardenpool_icon.png": "res://Models/Final Models/Backyard/FtrGardenpool/FtrGardenpool.tscn",
	"res://Models/Final Models/Backyard/FtrTopiaryRound/Textures/FtrTopiaryRound_icon.png": "res://Models/Final Models/Backyard/FtrTopiaryRound/FtrTopiaryRound.tscn",
	"res://Models/Final Models/Backyard/FtrSandbox/Textures/FtrSandbox_icon.png": "res://Models/Final Models/Backyard/FtrSandbox/FtrSandbox.tscn",
	"res://Models/Final Models/Backyard/FtrStoneChair/Textures/FtrStoneChair_icon.png": "res://Models/Final Models/Backyard/FtrStoneChair/FtrStoneChair.tscn",
	"res://Models/Final Models/Backyard/FtrStorage/Textures/FtrStorage_icon.png": "res://Models/Final Models/Backyard/FtrStorage/FtrStorage.tscn",
	"res://Models/Final Models/Backyard/FtrSwingWood/Textures/FtrSwingWood_icon.png": "res://Models/Final Models/Backyard/FtrSwingWood/FtrSwingWood.tscn",
	"res://Models/Final Models/Backyard/FtrGardenrockTall/Textures/FtrGardenrockTall_icon.png": "res://Models/Final Models/Backyard/FtrGardenrockTall/FtrGardenrockTall.tscn",
	"res://Models/Final Models/Backyard/FtrFirewood/Textures/FtrFirewood_icon.png": "res://Models/Final Models/Backyard/FtrFirewood/FtrFirewood.tscn",
	"res://Models/Final Models/Backyard/FtrBiotope/Textures/FtrBiotope_icon.png": "res://Models/Final Models/Backyard/FtrBiotope/FtrBiotope.tscn",
	"res://Models/Final Models/Backyard/FtrDwarf/Textures/FtrDwarf_icon.png": "res://Models/Final Models/Backyard/FtrDwarf/FtrDwarf.tscn",
	"res://Models/Final Models/Backyard/FtrNurseryplant/Textures/FtrNurseryplant_icon.png": "res://Models/Final Models/Backyard/FtrNurseryplant/FtrNurseryplant.tscn",
	"res://Models/Final Models/Backyard/FtrFlowerbed/Textures/FtrFlowerbed_icon.png": "res://Models/Final Models/Backyard/FtrFlowerbed/FtrFlowerbed.tscn",

	# Rugs
	"res://Models/Final Models/Rugs/RugSquareBrickS00/Textures/RugSquareBrickS00_icon.png": "res://Models/Final Models/Rugs/RugSquareBrickS00/RugSquareBrickS00.tscn",
	"res://Models/Final Models/Rugs/RugRectDeckM01/Textures/RugRectDeckM01_icon.png": "res://Models/Final Models/Rugs/RugRectDeckM01/RugRectDeckM01.tscn",
	"res://Models/Final Models/Rugs/RugRectDeckM02/Textures/RugRectDeckM02_icon.png": "res://Models/Final Models/Rugs/RugRectDeckM02/RugRectDeckM02.tscn",
	"res://Models/Final Models/Rugs/RugSquareStoneS00/Textures/RugSquareStoneS00_icon.png": "res://Models/Final Models/Rugs/RugSquareStoneS00/RugSquareStoneS00.tscn",
	"res://Models/Final Models/Rugs/RugSquareBrickS01/Textures/RugSquareBrickS01_icon.png": "res://Models/Final Models/Rugs/RugSquareBrickS01/RugSquareBrickS01.tscn",
	"res://Models/Final Models/Rugs/RugSquareStoneS01/Textures/RugSquareStoneS01_icon.png": "res://Models/Final Models/Rugs/RugSquareStoneS01/RugSquareStoneS01.tscn",
	"res://Models/Final Models/Rugs/RugRectDeckM00/Textures/RugRectDeckM00_icon.png": "res://Models/Final Models/Rugs/RugRectDeckM00/RugRectDeckM00.tscn",
	"res://Models/Final Models/Rugs/RugRectDeckM03/Textures/RugRectDeckM03_icon.png": "res://Models/Final Models/Rugs/RugRectDeckM03/RugRectDeckM03.tscn",
}
